#TG小钻风-大王叫我来巡山
[general]
udp_drop_list = STUN, QUIC
resource_parser_url= https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
geo_location_checker=http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/CC13594759/QuantumultX/main/IP-API.js
[dns]
no-system
server = 8.8.8.8
server = 223.5.5.5
[policy]
[server_local]
[server_remote]
#https://ss.hhyy.nn.kg/sub?token=f8ed344e6b2cf268b1af5b31aedebccd, tag=公益订阅, update-interval=172800, opt-parser=true, enabled=true
[filter_local]
final, proxy
[filter_remote]
https://raw.githubusercontent.com/CC13594759/QuantumultX/main/rule.list, tag=自用分流, update-interval=172800, opt-parser=false, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt, tag=国内IP, force-policy=direct, update-interval=172800, opt-parser=true, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/reject.txt, tag=广告, force-policy=reject, update-interval=172800, opt-parser=true, enabled=true
[rewrite_local]
^https:\/\/api\.pingmeapp\.net\/app\/queryBalanceAndBonus url script-request-header https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/PingMe.js
[rewrite_remote]
https://ddgksf2013.top/rewrite/StartUpAds.conf, tag=墨鱼去开屏, update-interval=172800, opt-parser=false, enabled=true
https://github.com/NSRingo/WeatherKit/releases/latest/download/iRingo.WeatherKit.snippet, tag=天气, update-interval=172800, opt-parser=false, enabled=true
https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/Youtube.snippet, tag=YouTube去广告, update-interval=172800, opt-parser=true, enabled=true
[task_local]
event-interaction https://raw.githubusercontent.com/CC13594759/QuantumultX/main/network-info.js, tag=网络信息 𝕏, enabled=true
event-interaction https://raw.githubusercontent.com/CC13594759/QuantumultX/main/IPPure.js, tag=节点详情(IPPure), enabled=true
10 */4 * * * https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/PingMe.js, tag=PingMe签到, enabled=true
[http_backend]
[mitm]
passphrase = 
p12 = 
hostname = api.pingmeapp.net
