#TG小钻风-大王叫我来巡山
[general]
udp_drop_list = STUN, QUIC
excluded_routes = 192.168.0.0/16
resource_parser_url= https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
geo_location_checker=http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/CC13594759/QuantumultX/main/IP-API.js
[dns]
no-system
server = 8.8.8.8
server = 223.5.5.5
[policy]
static=抖音, direct, auto
static=auto, server-tag-regex=^
[server_local]
[server_remote]
https://lol.mmhh.eu.cc/hhlfy2026124/clash, tag=Tag-1778304531, update-interval=172800, opt-parser=true, enabled=true
[filter_local]
final, proxy
[filter_remote]
https://raw.githubusercontent.com/CC13594759/QuantumultX/main/rule.list, tag=自用分流, update-interval=172800, opt-parser=false, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt, tag=国内IP, force-policy=direct, update-interval=172800, opt-parser=true, enabled=true
https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/reject.txt, tag=广告, force-policy=reject, update-interval=172800, opt-parser=true, enabled=true
[rewrite_local]
[rewrite_remote]
https://github.com/NSRingo/WeatherKit/releases/latest/download/iRingo.WeatherKit.snippet, tag=天气, update-interval=172800, opt-parser=false, enabled=true
https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Enhance.sgmodule, tag=YouTube去广告, update-interval=172800, opt-parser=true, enabled=true
[task_local]
event-interaction https://raw.githubusercontent.com/CC13594759/QuantumultX/main/network-info.js, tag=网络信息 𝕏, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png, enabled=true
event-interaction https://raw.githubusercontent.com/CC13594759/QuantumultX/main/IPPure.js, tag=节点详情(IPPure), img-url=checkmark.shield.fill.system
[http_backend]
[mitm]
passphrase = 
p12 = 